name: Feature Pipeline

on:
  schedule:
    - cron: "*/5 * * * *"   # every hour
  workflow_dispatch:

jobs:
  feature-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install deps
      run: pip install pandas scikit-learn joblib

    - name: Run feature pipeline
      run: python scripts/aqi_features.py
