name: Training Pipeline

on:
  schedule:
    - cron: "0 2 * * *"   # At 02:00 AM
  workflow_dispatch:

jobs:
  train-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install tensorflow hopsworks joblib

      - name: Run training pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          WAQI_API_KEY: ${{ secrets.WAQI_API_KEY }}
        run: python scripts/aqi_training.py
       
      - name: Upload SHAP plots
        uses: actions/upload-artifact@v4
        with:
          name: shap-plots
          path: shap_plots/   